# ==============================================================================
# Service: third-party-utility-service (Port: 8087)
# Example API Calls:
#   POST http://localhost:8087/third-party/flight/search-pnr
#   POST http://localhost:8087/third-party/watchlist/check
# ==============================================================================
server:
  port: 8087

spring:
  application:
    name: third-party-utility-service
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres?TimeZone=Asia/Kolkata
    username: postgres
    password: root
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true

springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics
